# Generated by Django 3.2.7 on 2021-10-11 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worlds.medium')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfFiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('length', models.IntegerField(null=True)),
                ('pub_date', models.DateField()),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.medium')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.universe')),
            ],
            options={
                'verbose_name_plural': 'units of fiction',
                'order_with_respect_to': 'universe',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('appearances', models.ManyToManyField(to='worlds.UnitOfFiction')),
                ('friends', models.ManyToManyField(related_name='_worlds_character_friends_+', to='worlds.Character')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.universe')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('unitoffiction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='worlds.unitoffiction')),
                ('number', models.CharField(max_length=10)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.series')),
            ],
            bases=('worlds.unitoffiction',),
        ),
    ]
